name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get -qyy install pandoc wkhtmltopdf
    - run: pandoc incoming/brief_beispiel.md -o foo.html --template=templates/template_brief.htm        
    - run: wkhtmltopdf --enable-local-file-access foo.html foo.pdf
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: foo*
